//created on: Oct 24, 2025
package rule

//list any import classes here.
import elem.ECG
import diagnosticos.*
import patrones.*


//declare any global variables here



rule "Taquicardia"
	agenda-group "Reglas_Diagnosticos"
	
    when 
		$p :FrecuenciaCardiacaAlta()
	then 
		Taquicardia d = new Taquicardia($p.getConfianza(),$p);
		insert(d);
end

rule "Bradicardia"
	agenda-group "Reglas_Diagnosticos"
	
    when 
		$p :FrecuenciaCardiacaBaja()
	then 
		Bradicardia d = new Bradicardia($p.getConfianza(),$p);
		insert(d);
end

rule "Hipocalcemia"
	agenda-group "Reglas_Diagnosticos"
	
    when 
		$p : IntervaloQtAlargado()
	then 
		Hipocalcemia d = new Hipocalcemia($p.getConfianza(),$p);
		insert(d);
end

rule "Hipopotasemia"
	agenda-group "Reglas_Diagnosticos"
	
    when 
		$p : OndaTMuyAplanada()
	then 
		Hipopotasemia d = new Hipopotasemia($p.getConfianza(),$p);
		insert(d);
end

rule "Isquemia Coronaria"
	agenda-group "Reglas_Diagnosticos"
	
    when 
		$p : OndaTAplanada()
	then 
		IsquemiaCoronaria d = new IsquemiaCoronaria($p.getConfianza(),$p);
		insert(d);
end

rule "Infarto Agudo de Miocardio"
agenda-group "Reglas_Diagnosticos"
	
    when 
		$p : OndaTHiperaguda()
	then 
		InfartoAgudoMiocardio d = new InfartoAgudoMiocardio($p.getConfianza(),$p);
		insert(d);
end

rule "Contracción Ventricular Prematura"
agenda-group "Reglas_Diagnosticos"

	when
		$p : ComplejoQrsAcortado()
	then 
		ContraccionVentricularPrematura d = new ContraccionVentricularPrematura($p.getConfianza(),$p);
		insert(d);
end	

