//created on: Oct 24, 2025
package rule

//list any import classes here.
import elem.ECG
import diagnosticos.*


//declare any global variables here



rule "Taquicardia"
	agenda-group "Reglas_Diagnosticos"
	
    when 
		$Patron : PatronPatologico(tipo == TipoPatron.FRECUENCIA_CARDIACA_ALTA)
	then 
		Diagnostico d = new Diagnostico(1,$Patron,TipoDiagnostico.TAQUICARDIA,$Patron.getSeveridad());
		insert(d);
end

rule "Bradicardia"
	agenda-group "Reglas_Diagnosticos"
	
    when 
		$Patron : PatronPatologico(tipo == TipoPatron.FRECUENCIA_CARDIACA_BAJA)
	then 
		Diagnostico d = new Diagnostico(1,$Patron,TipoDiagnostico.BRADICARDIA,$Patron.getSeveridad());
		insert(d);
end

rule "Hipocalcemia"
	agenda-group "Reglas_Diagnosticos"
	
    when 
		$Patron : PatronPatologico(tipo == TipoPatron.INTERVALO_QT_ALARGADO)
	then 
		Diagnostico d = new Diagnostico(1,$Patron,TipoDiagnostico.HIPOCALCEMIA,$Patron.getSeveridad());
		insert(d);
end

rule "Hipopotasemia"
	agenda-group "Reglas_Diagnosticos"
	
    when 
		$Patron : PatronPatologico(tipo == TipoPatron.ONDA_T_MUY_APLANADA)
	then 
		Diagnostico d = new Diagnostico(1,$Patron,TipoDiagnostico.HIPOPOTASEMIA,$Patron.getSeveridad());
		insert(d);
end

rule "Isquemia Coronaria"
	agenda-group "Reglas_Diagnosticos"
	
    when 
		$Patron : PatronPatologico(tipo == TipoPatron.ONDA_T_APLANADA)
	then 
		Diagnostico d = new Diagnostico(1,$Patron,TipoDiagnostico.ISQUEMIA_CORONARIA,$Patron.getSeveridad());
		insert(d);
end

rule "Infarto Agudo de Miocardio"
agenda-group "Reglas_Diagnosticos"
	
    when 
		$Patron : PatronPatologico(tipo == TipoPatron.ONDA_T_HIPERAGUDA)
	then 
		Diagnostico d = new Diagnostico(1,$Patron,TipoDiagnostico.INFARTO_AGUDO_DE_MIOCARDIO,$Patron.getSeveridad());
		insert(d);
end

rule "Contracción Ventricular Prematura"
agenda-group "Reglas_Diagnosticos"

	when
		$Patron : PatronPatologico(tipo == TipoPatron.COMPLEJO_QRS_ACORTADO)
	then 
		Diagnostico d = new Diagnostico(1,$Patron,TipoDiagnostico.CONTRACCION_VENTRICULAR_PREMATURA,$Patron.getSeveridad());
		insert(d);
end	

