//created on: Oct 23, 2025
package rulesDSI

//list any import classes here.
import dsi.Person;


//declare any global variables here




rule "Print a persons"

    when
        p: Person()
    then
        System.out.println("Hello "+ p.getName());

end

rule "UpToDate Adults"
    //include attributes such as "salience" here...
    when
        p: Person(age >=18 , adult == false)
    then
        modify(p){
        	setAdult(true);
        }
        System.out.println("Uploaded adult "+ p.getName());

end
