//created on: Oct 24, 2025
package rule

//list any import classes here.
import elem.ECG
import elem.Ciclo
import diagnosticos.*
import componentes.*


//declare any global variables here



rule "Frecuencia cardiaca alta"
	agenda-group "Reglas_Patrones"
	
    when 
		$ECG : ECG(frecuenciaCardiaca >= 100)
	then 
		PatronPatologico p = new PatronPatologico(Severidad.ALTA,null,TipoPatron.FRECUENCIA_CARDIACA_ALTA);
		insert(p);
end

rule "Frecuencia cardiaca baja"
	agenda-group "Reglas_Patrones"
	
    when 
		$ECG : ECG(frecuenciaCardiaca <= 60)
	then 
		PatronPatologico p = new PatronPatologico(Severidad.ALTA,null,TipoPatron.FRECUENCIA_CARDIACA_BAJA);
		insert(p);
end

rule "Intervalo QT alargado"
	agenda-group "Reglas_Patrones"
	
	when
		$c : Ciclo(intervaloQT != null, intervaloQT.duracion>500)
		not (PatronPatologico(tipo == TipoPatron.INTERVALO_QT_ALARGADO))
	then
		PatronPatologico p = new PatronPatologico(Severidad.ALTA,null,TipoPatron.INTERVALO_QT_ALARGADO);
		insert(p);
end

rule "Onda T muy Aplanada"
agenda-group "Reglas_Patrones"
	

	when
    	$t : Onda(tipo == OndaTipo.T,amplitud < -14)
    	not  (PatronPatologico(tipo == TipoPatron.ONDA_T_MUY_APLANADA))
	then
    	PatronPatologico p = new PatronPatologico(Severidad.ALTA,null,TipoPatron.ONDA_T_MUY_APLANADA);
		insert(p);
end

rule "Onda T Aplanada"
agenda-group "Reglas_Patrones"
	
	when
    	$t : Onda(tipo == OndaTipo.T,-14 < amplitud,amplitud < -9)
    	not  (PatronPatologico(tipo == TipoPatron.ONDA_T_APLANADA))
	then
    	PatronPatologico p = new PatronPatologico(Severidad.ALTA,null,TipoPatron.ONDA_T_APLANADA);
		insert(p);
	end

rule "Onda T Hiperaguda"
agenda-group "Reglas_Patrones"
	
	when 
		$t : Onda(tipo == OndaTipo.T, amplitud > 10)
		not (PatronPatologico(tipo == TipoPatron.ONDA_T_HIPERAGUDA))
	then 
		PatronPatologico p = new PatronPatologico(Severidad.ALTA,null,TipoPatron.ONDA_T_HIPERAGUDA);
		insert(p);
end

rule "Complejo QRS acortado"
agenda-group "Reglas_Patrones"
	
	when
		$c : Ciclo(complejoQRS != null, complejoQRS.duracion<90)
		not (PatronPatologico(tipo == TipoPatron.COMPLEJO_QRS_ACORTADO))
	then 
		
		PatronPatologico p = new PatronPatologico(Severidad.ALTA,null,TipoPatron.COMPLEJO_QRS_ACORTADO);
		insert(p);
end	
			
