package diagnosticos;

public enum TipoPatron {
    INTERVALO_QT_ALARGADO, 
    COMPLEJO_QRS_ACORTADO, 
    ONDA_T_APLANADA, 
    ONDA_T_MUY_APLANADA,
    ONDA_T_HIPERAGUDA,
	FRECUENCIA_CARDIACA_ALTA,
	FRECUENCIA_CARDIACA_BAJA;
}
