package diagnosticos;

public enum TipoDiagnostico {
	
	ALETEO_AURICULAR,
	BRADICARDIA,
	CONTRACCION_VENTRICULAR_PREMATURA,
	HIPOCALCEMIA,
	HIPOPOTASEMIA,
	INFARTO_AGUDO_DE_MIOCARDIO,
	ISQUEMIA_CORONARIA,
	TAQUICARDIA

}
